### ISSUE TITLE
Importing database scheme

### ISSUE THREAD

**Issue by mjpikat** [endre86/puckno_tournament#1]
Hi!

During import of database scheme I am facing this:
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET utf8 NOT NULL,

  `name` varchar(255) CHARACTER SET utf8 NOT NULL,
' at line 3

I have PHP version: 5.5.26, database client version: libmysql - 5.6.22.

**Comment by endre86** [comment]
Hi. Sorry for such a late reply. If you are still interested, this DB scheme should work. I have included one scheme only file and one with some test data.

If you are interested, I am working on a new version. Probably won't be finished in a while though.
[db scheme.txt](https://github.com/endre86/puckno_tournament/files/129670/db.scheme.txt)
[dcb scheme with data.txt](https://github.com/endre86/puckno_tournament/files/129673/dcb.scheme.with.data.txt)
